name: Rust

on:
  release:
    types: [created]
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux_x86_64:

    runs-on: [self-hosted, linux, X64]

    steps:
    - uses: actions/checkout@v4

    #- name: Build
    #  run: cargo build --verbose

    #- name: Run tests
    #  run: cargo test --verbose

    - name: Release
      run: rustup default stable && cargo build --release

    - name: Move Binary (on success)
      run: |
        mkdir -p releases/linux_x86_64
        mv target/release/moblink-rust-relay releases/linux_x86_64/moblink-rust-relay

    - name: Commit and Push Binary
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add releases/linux_x86_64/moblink-rust-relay
        git commit -m "Update X64 binary for latest release" || echo "No changes to commit"
        git push origin HEAD:${{ github.ref_name }}
  build_linux_arm64:

    runs-on: [self-hosted, linux, ARM64]

    steps:
    - uses: actions/checkout@v4

    #- name: Build
    #  run: cargo build --verbose

    #- name: Run tests
    #  run: cargo test --verbose

    - name: Release
      run: rustup default stable && cargo build --release

    - name: Move Binary (on success)
      run: |
        mkdir -p releases/linux_arm64
        mv target/release/moblink-rust-relay releases/linux_arm64/moblink-rust-relay

    - name: Commit and Push Binary
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add releases/linux_arm64/moblink-rust-relay
        git commit -m "Update ARM64 binary for latest release" || echo "No changes to commit"
        git push origin HEAD:${{ github.ref_name }}
